import os
import platform
print('processor is -->',platform.processor())
print("                                               ")
print("-----------------------------------------------------------------------")
print("                                                                         ")
print("machine's architecture is",platform.architecture())
print("                                               ")
print("-------------------------------------------------------------------")
print("                                                                     ")
print("system's information is",platform.platform())
print("                                               ")
print("-------------------------------------------------------------------")
print("                                                                     ")
print("system processor is --->",platform.processor())
print("                                               ")
print("-------------------------------------------------------------------")
print("                                                                     ")
print("system operating system(os) is --->",platform.system())
print("                                               ")
print("-------------------------------------------------------------------")
print("                                                                     ")
print("python build date and number is --->",platform.python_build())
print("                                               ")
print("-------------------------------------------------------------------")
print("                                                                     ")
print("Python compiler is --->",platform.python_compiler())
print("                                               ")
print("-------------------------------------------------------------------")
print("                                                                     ")
print("system username is --->",platform.uname())
print("                                               ")
print("-------------------------------------------------------------------")
print("                                                                     ")
print("system's current version is --->",platform.version())
print("                                               ")
print("-------------------------------------------------------------------")
print("                                                                     ")
x = os.system('systeminfo')
print(x)
print(                                                                   )
print("--------------------------------------------------------------------------")
print("                                                                             ")
print("Note :--- \n Use this module for educational purpose / for ethic ways \n for any kind of illegal activities iam not responsible.")
print(" ")
print("----------------------------------------------------------------------------------")
print("       ")
print("""sysinfo Module by "JustVedant" """)
print("Easy to use by importing module and simply run the program without \n sysntax to get system information")
print(" ")
print(" ")
print("module version 1.1 \n hey wait wait wait dear programers v1.2 of this module will get release oa soon as possible.")